format = '$all$username[::](bold blue)$hostname$character'

[kubernetes]
disabled = false

[username]
disabled = false
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
ssh_symbol = ' 🌐'
format = '[$hostname](bold purple)[$ssh_symbol](bold blue)'
trim_at = '.local'
disabled = false
